#!/bin/bash
# vim: fdm=marker fmr={{{,}}} fenc=utf-8

MC_CONFIG_INSTANCE='bukkit'
MC_CONFIG_INSTANCE_FOLDER_NAME="$MC_CONFIG_INSTANCE"
MC_CONFIG_BACKUP_INSTANCE_FOLDER_NAME="$MC_CONFIG_INSTANCE"

MC_CONFIG_UID='mc'
MC_CONFIG_JAR='spigot.jar'
MC_CONFIG_MIN_STACK='1G'
MC_CONFIG_MAX_STACK='5G'

MC_CONFIG_TMUX_SESSION='minecraft'
MC_CONFIG_TMUX_WINDOW="$MC_CONFIG_INSTANCE"

MC_CONFIG_RESTART_DELAY=3

